// SA_SaleOrder_code: "2019120001"
// SA_SaleOrder_name: null
// SA_SaleOrder_discountRate: 1
// SA_SaleOrder_discountAmount: null
// SA_SaleOrder_origDiscountAmount: null
// SA_SaleOrder_exchangeRate: 1
// SA_SaleOrder_address: "河南省周口市鹿邑县产业集聚区志元大道与恒丰路口"
// SA_SaleOrder_linkMan: "丁文举"
// SA_SaleOrder_contractCode: ""
// SA_SaleOrder_origEarnestMoney: 0
// SA_SaleOrder_earnestMoney: 0
// SA_SaleOrder_memo: ""
// SA_SaleOrder_origAmount: 26548.67
// SA_SaleOrder_amount: 26548.67
// SA_SaleOrder_origTaxAmount: 30000
// SA_SaleOrder_taxAmount: 30000
// SA_SaleOrder_contactPhone: "17698591188"
// SA_SaleOrder_maker: "demo"
// SA_SaleOrder_auditor: "demo"
// SA_SaleOrder_reviser: "demo"
// SA_SaleOrder_iscarriedforwardout: 0
// SA_SaleOrder_iscarriedforwardin: 0
// SA_SaleOrder_ismodifiedcode: 0
// SA_SaleOrder_docid: null
// SA_SaleOrder_ts: Object
// SA_SaleOrder_updatedBy: "demo"
// SA_SaleOrder_priuserdefnvc1: ""
// SA_SaleOrder_priuserdefdecm1: null
// SA_SaleOrder_priuserdefnvc2: ""
// SA_SaleOrder_priuserdefdecm2: null
// SA_SaleOrder_priuserdefnvc3: "签单，盖章，运费我司付"
// SA_SaleOrder_priuserdefdecm3: null
// SA_SaleOrder_priuserdefnvc4: ""
// SA_SaleOrder_priuserdefdecm4: null
// SA_SaleOrder_priuserdefnvc5: ""
// SA_SaleOrder_priuserdefdecm5: null
// SA_SaleOrder_priuserdefnvc6: null
// SA_SaleOrder_priuserdefdecm6: null
// SA_SaleOrder_pubuserdefnvc1: ""
// SA_SaleOrder_pubuserdefdecm1: null
// SA_SaleOrder_pubuserdefnvc2: null
// SA_SaleOrder_pubuserdefdecm2: null
// SA_SaleOrder_pubuserdefnvc3: ""
// SA_SaleOrder_pubuserdefdecm3: null
// SA_SaleOrder_pubuserdefnvc4: null
// SA_SaleOrder_pubuserdefdecm4: null
// SA_SaleOrder_pubuserdefnvc5: null
// SA_SaleOrder_pubuserdefdecm5: null
// SA_SaleOrder_pubuserdefnvc6: null
// SA_SaleOrder_pubuserdefdecm6: null
// SA_SaleOrder_IsAutoGenerateSaleOrderBOM: 0
// SA_SaleOrder_IsAutoGenerateRouting: 0
// SA_SaleOrder_SourceVoucherCode: null
// SA_SaleOrder_isnomodify: null
// SA_SaleOrder_changer: ""
// SA_SaleOrder_Mobilephone: null
// SA_SaleOrder_MemberAddress: ""
// SA_SaleOrder_PrintCount: 0
// SA_SaleOrder_IsSeparateByWareHouse: 0
// SA_SaleOrder_OrigReceiveAmount: 0
// SA_SaleOrder_ReceiveAmount: 0
// SA_SaleOrder_collaborateVoucherCode: ""
// SA_SaleOrder_ExternalCode: null
// SA_SaleOrder_ID: 1
// SA_SaleOrder_idbusinesstype: 65
// SA_SaleOrder_idcurrency: 4
// SA_SaleOrder_iddepartment: 16
// SA_SaleOrder_IdMember: null
// SA_SaleOrder_idmarketingOrgan: 1
// SA_SaleOrder_idcustomer: 2801
// SA_SaleOrder_idsettlecustomer: 2801
// SA_SaleOrder_idclerk: 23
// SA_SaleOrder_idproject: null
// SA_SaleOrder_idwarehouse: 29
// SA_SaleOrder_idCollaborateUpVoucherType: null
// SA_SaleOrder_idCollaborateUpVoucher: null
// SA_SaleOrder_DataSource: 1531
// SA_SaleOrder_deliveryMode: null
// SA_SaleOrder_isCancel: null
// SA_SaleOrder_isSaleDelivery: null
// SA_SaleOrder_isSaleOut: null
// SA_SaleOrder_reciveType: 76
// SA_SaleOrder_voucherState: 189
// SA_SaleOrder_auditorid: 22
// SA_SaleOrder_makerid: 22
// SA_SaleOrder_changerid: null
// SA_SaleOrder_idCollaborateDownVoucherType: null
// SA_SaleOrder_CollaborateState: null
// SA_SaleOrder_idCollaborateDownDraftVoucher: null
// SA_SaleOrder_SourceVoucherID: null
// SA_SaleOrder_idsourcevouchertype: null
// SA_SaleOrder_deliveryDate: "2019-12-26T00:00:00.000Z"
// SA_SaleOrder_voucherdate: "2019-12-02T00:00:00.000Z"
// SA_SaleOrder_madedate: "2019-12-05T00:00:00.000Z"
// SA_SaleOrder_auditeddate: "2019-12-25T00:00:00.000Z"
// SA_SaleOrder_createdtime: "2019-12-05T15:08:22.660Z"
// SA_SaleOrder_updated: "2020-01-02T19:37:04.590Z"
// SA_SaleOrder_changedate: null
// SA_SaleOrder_ExternalVoucherCode: ""
// SA_SaleOrder_CustomerPhone: ""
// SA_SaleOrder_HasRecordCredit: true
// SA_SaleOrder_IsAutoWarehouse: false
// SA_SaleOrder_InputDataSource: null
// SA_SaleOrder_Closer: null
// SA_SaleOrder_CloseDate: null
// SA_SaleOrder_pubuserdefnvc7: null
// SA_SaleOrder_b_code: "0000"
// SA_SaleOrder_b_quantity: 300
// SA_SaleOrder_b_quantity2: null
// SA_SaleOrder_b_baseQuantity: 300
// SA_SaleOrder_b_subQuantity: null
// SA_SaleOrder_b_compositionQuantity: "300个"
// SA_SaleOrder_b_origPrice: null
// SA_SaleOrder_b_price: null
// SA_SaleOrder_b_basePrice: null
// SA_SaleOrder_b_discountRate: 1
// SA_SaleOrder_b_origDiscountPrice: 88.49558
// SA_SaleOrder_b_discountPrice: 88.49558
// SA_SaleOrder_b_baseDiscountPrice: null
// SA_SaleOrder_b_taxRate: 0.13
// SA_SaleOrder_b_origTaxPrice: 100
// SA_SaleOrder_b_taxPrice: 100
// SA_SaleOrder_b_baseTaxPrice: null
// SA_SaleOrder_b_origDiscountAmount: 26548.67
// SA_SaleOrder_b_discountAmount: 26548.67
// SA_SaleOrder_b_origTax: 3451.33
// SA_SaleOrder_b_tax: 3451.33
// SA_SaleOrder_b_origTaxAmount: 30000
// SA_SaleOrder_b_taxAmount: 30000
// SA_SaleOrder_b_isPresent: 0
// SA_SaleOrder_b_manufactureQuantity: null
// SA_SaleOrder_b_manufactureQuantity2: null
// SA_SaleOrder_b_purchaseQuantity: null
// SA_SaleOrder_b_purchaseQuantity2: null
// SA_SaleOrder_b_deliveryQuantity: null
// SA_SaleOrder_b_deliveryQuantity2: null
// SA_SaleOrder_b_saleOutQuantity: null
// SA_SaleOrder_b_saleOutQuantity2: null
// SA_SaleOrder_b_executedQuantity: null
// SA_SaleOrder_b_executedQuantity2: null
// SA_SaleOrder_b_unitExchangeRate: null
// SA_SaleOrder_b_origDiscount: null
// SA_SaleOrder_b_discount: null
// SA_SaleOrder_b_taxFlag: 1
// SA_SaleOrder_b_inventoryBarCode: null
// SA_SaleOrder_b_partnerInventoryCode: null
// SA_SaleOrder_b_ts: Object
// SA_SaleOrder_b_updatedBy: "demo"
// SA_SaleOrder_b_freeItem0: null
// SA_SaleOrder_b_freeItem1: null
// SA_SaleOrder_b_freeItem2: null
// SA_SaleOrder_b_freeItem3: null
// SA_SaleOrder_b_freeItem4: null
// SA_SaleOrder_b_freeItem5: null
// SA_SaleOrder_b_freeItem6: null
// SA_SaleOrder_b_freeItem7: null
// SA_SaleOrder_b_freeItem8: null
// SA_SaleOrder_b_freeItem9: null
// SA_SaleOrder_b_priuserdefnvc1: "R229钛白粉"
// SA_SaleOrder_b_priuserdefdecm1: 12
// SA_SaleOrder_b_priuserdefnvc2: null
// SA_SaleOrder_b_priuserdefdecm2: null
// SA_SaleOrder_b_priuserdefnvc3: null
// SA_SaleOrder_b_priuserdefdecm3: null
// SA_SaleOrder_b_priuserdefnvc4: "61袋"
// SA_SaleOrder_b_priuserdefdecm4: 0.3
// SA_SaleOrder_b_pubuserdefnvc1: null
// SA_SaleOrder_b_pubuserdefdecm1: null
// SA_SaleOrder_b_pubuserdefnvc2: null
// SA_SaleOrder_b_pubuserdefdecm2: null
// SA_SaleOrder_b_pubuserdefnvc3: null
// SA_SaleOrder_b_pubuserdefdecm3: null
// SA_SaleOrder_b_pubuserdefnvc4: null
// SA_SaleOrder_b_pubuserdefdecm4: null
// SA_SaleOrder_b_partnerInventoryName: null
// SA_SaleOrder_b_HasPRA: 0
// SA_SaleOrder_b_prarequiretimes: 0
// SA_SaleOrder_b_hasorderbom: null
// SA_SaleOrder_b_isnomodify: null
// SA_SaleOrder_b_SourceVoucherCode: null
// SA_SaleOrder_b_detailVoucherState: null
// SA_SaleOrder_b_Retailprice: null
// SA_SaleOrder_b_DistributionQuantity: null
// SA_SaleOrder_b_DistributionQuantity2: null
// SA_SaleOrder_b_PriceStrategyTypeName: ""
// SA_SaleOrder_b_PriceStrategySchemeIds: ""
// SA_SaleOrder_b_PriceStrategySchemeNames: ""
// SA_SaleOrder_b_PromotionVoucherCodes: ""
// SA_SaleOrder_b_PromotionVoucherIds: ""
// SA_SaleOrder_b_IsMemberIntegral: 0
// SA_SaleOrder_b_IsPromotionPresent: 0
// SA_SaleOrder_b_PromotionPresentVoucherCode: null
// SA_SaleOrder_b_PromotionSingleVoucherCode: ""
// SA_SaleOrder_b_PromotionPresentGroupID: null
// SA_SaleOrder_b_PromotionSingleGroupID: null
// SA_SaleOrder_b_DetailMemo: null
// SA_SaleOrder_b_id: 1
// SA_SaleOrder_b_idbom: null
// SA_SaleOrder_b_idinventory: 330
// SA_SaleOrder_b_idproject: null
// SA_SaleOrder_b_idbaseunit: 2
// SA_SaleOrder_b_idsubunit: null
// SA_SaleOrder_b_idunit: 2
// SA_SaleOrder_b_idunit2: null
// SA_SaleOrder_b_idwarehouse: 29
// SA_SaleOrder_b_CashbackWay: null
// SA_SaleOrder_b_PriceStrategyTypeId: null
// SA_SaleOrder_b_PromotionPresentTypeID: null
// SA_SaleOrder_b_PromotionSingleTypeID: null
// SA_SaleOrder_b_PromotionPresentVoucherID: null
// SA_SaleOrder_b_PromotionSingleVoucherID: null
// SA_SaleOrder_b_idSaleOrderDTO: 1
// SA_SaleOrder_b_SourceVoucherId: null
// SA_SaleOrder_b_SourceVoucherDetailId: null
// SA_SaleOrder_b_iddestvouchertype: null
// SA_SaleOrder_b_idsourcevouchertype: null
// SA_SaleOrder_b_deliveryDate: "2019-12-26T00:00:00.000Z"
// SA_SaleOrder_b_updated: "2020-01-02T19:35:20.923Z"
// SA_SaleOrder_b_LatestCost: null
// SA_SaleOrder_b_LatestPOrigTaxPrice: null
// SA_SaleOrder_b_LatestSaleOrigTaxPrice: null
// SA_SaleOrder_b_LowestSalePrice: null
// SA_SaleOrder_b_SingleInvGrossProfit: null
// SA_SaleOrder_b_GrossProfit: null
// SA_SaleOrder_b_GrossProfitRate: null
// SA_SaleOrder_b_DataSource: 1531
// SA_SaleOrder_b_IsClose: 0
// SA_SaleOrder_b_IsModifiedPrice: 1
// SA_SaleOrder_b_Closer: null
// SA_SaleOrder_b_CloseDate: null
// AA_Inventory_code: "61袋"
// AA_Inventory_name: "R229钛白粉"
// AA_Inventory_shorthand: "R229TBF"
// AA_Inventory_specification: null
// AA_Inventory_procureBatch: null
// AA_Inventory_invSCost: null
// AA_Inventory_latestCost_Abandon: null
// AA_Inventory_avagCost_Abandon: null
// AA_Inventory_isLimitedWithdraw: 0
// AA_Inventory_isBatch: 1
// AA_Inventory_isQualityPeriod: 0
// AA_Inventory_isSale: 1
// AA_Inventory_isMadeSelf: 1
// AA_Inventory_isPurchase: 1
// AA_Inventory_isMaterial: 1
// AA_Inventory_lowQuantity: null
// AA_Inventory_topQuantity: null
// AA_Inventory_safeQuantity: null
// AA_Inventory_picture: null
// AA_Inventory_disabled: 0
// AA_Inventory_isQualityCheck: 0
// AA_Inventory_isMadeRequest: 0
// AA_Inventory_isSingleUnit: 1
// AA_Inventory_ts: Object
// AA_Inventory_updatedBy: "888"
// AA_Inventory_Userfreeitem7: 0
// AA_Inventory_Userfreeitem6: 0
// AA_Inventory_Userfreeitem2: 0
// AA_Inventory_Userfreeitem1: 0
// AA_Inventory_Userfreeitem9: 0
// AA_Inventory_Userfreeitem0: 0
// AA_Inventory_Userfreeitem8: 0
// AA_Inventory_Userfreeitem5: 0
// AA_Inventory_Userfreeitem4: 0
// AA_Inventory_Userfreeitem3: 0
// AA_Inventory_MustInputFreeitem7: 0
// AA_Inventory_MustInputFreeitem2: 0
// AA_Inventory_MustInputFreeitem6: 0
// AA_Inventory_MustInputFreeitem3: 0
// AA_Inventory_MustInputFreeitem5: 0
// AA_Inventory_MustInputFreeitem4: 0
// AA_Inventory_MustInputFreeitem9: 0
// AA_Inventory_MustInputFreeitem1: 0
// AA_Inventory_MustInputFreeitem8: 0
// AA_Inventory_MustInputFreeitem0: 0
// AA_Inventory_produceBatch: null
// AA_Inventory_imageFile: null
// AA_Inventory_priuserdefnvc1: null
// AA_Inventory_priuserdefdecm1: 25
// AA_Inventory_priuserdefnvc2: null
// AA_Inventory_priuserdefdecm2: null
// AA_Inventory_priuserdefnvc3: null
// AA_Inventory_priuserdefdecm3: null
// AA_Inventory_priuserdefnvc4: null
// AA_Inventory_priuserdefdecm4: null
// AA_Inventory_priuserdefnvc5: null
// AA_Inventory_priuserdefdecm5: null
// AA_Inventory_standardturnoverdays: null
// AA_Inventory_HasEverChanged: "1"
// AA_Inventory_pickbatch: null
// AA_Inventory_isphantom: 0
// AA_Inventory_ControlRangeFreeitem0: 0
// AA_Inventory_ControlRangeFreeitem1: 0
// AA_Inventory_ControlRangeFreeitem2: 0
// AA_Inventory_ControlRangeFreeitem3: 0
// AA_Inventory_ControlRangeFreeitem4: 0
// AA_Inventory_ControlRangeFreeitem5: 0
// AA_Inventory_ControlRangeFreeitem6: 0
// AA_Inventory_ControlRangeFreeitem7: 0
// AA_Inventory_ControlRangeFreeitem8: 0
// AA_Inventory_ControlRangeFreeitem9: 0
// AA_Inventory_IsLaborCost: 0
// AA_Inventory_BatchRunNumber: 0
// AA_Inventory_IsNew: 0
// AA_Inventory_MadeRecordDate: "2018-11-30T15:58:52.000Z"
// AA_Inventory_InventoryDescript: null
// AA_Inventory_ReNewGoodSellDays: null
// AA_Inventory_ReNewGoodAheadDays: null
// AA_Inventory_IsSuite: 0
// AA_Inventory_IsWeigh: 0
// AA_Inventory_DefaultBarCode: null
// AA_Inventory_NewProductPeriod: null
// AA_Inventory_Expired: null
// AA_Inventory_idbarcodesolution: null
// AA_Inventory_id: 330
// AA_Inventory_idinventoryclass: 4
// AA_Inventory_idinvlocation: null
// AA_Inventory_idMarketingOrgan: 1
// AA_Inventory_idpartner: null
// AA_Inventory_idunit: 2
// AA_Inventory_idunitbymanufacture: 2
// AA_Inventory_idUnitByPurchase: 2
// AA_Inventory_idUnitByRetail: 2
// AA_Inventory_idUnitBySale: 2
// AA_Inventory_idUnitByStock: 2
// AA_Inventory_idunitgroup: null
// AA_Inventory_idSubUnitByReport: null
// AA_Inventory_ExpiredUnit: null
// AA_Inventory_idwarehouse: 29
// AA_Inventory_customerReplenishmentRule: null
// AA_Inventory_pickbatchmethod: null
// AA_Inventory_planattribute: null
// AA_Inventory_productInfo: null
// AA_Inventory_storeReplenishmentRule: null
// AA_Inventory_taxRate: 351
// AA_Inventory_unittype: 595
// AA_Inventory_valueType: 423
// AA_Inventory_madeDate: "2018-11-30T15:58:51.000Z"
// AA_Inventory_updated: "2018-11-30T15:58:51.000Z"
// AA_Inventory_createdTime: "2018-11-30T15:58:51.000Z"
// AA_Inventory_Creater: "廖杰"
// AA_Inventory_Changer: "崔梦莉"
// AA_Inventory_Changedate: "2019-11-09T16:00:36.000Z"
// AA_Inventory_JinShuiCode: null
// AA_Inventory_IsModifiedCode: 1
// AA_Inventory_WithOutBargain: null
// AA_Inventory_idInventoryFreeItemClass0: null
// AA_Inventory_idInventoryFreeItemClass1: null
// AA_Inventory_idInventoryFreeItemClass2: null
// AA_Inventory_idInventoryFreeItemClass3: null
// AA_Inventory_idInventoryFreeItemClass4: null
// AA_Inventory_idInventoryFreeItemClass5: null
// AA_Inventory_idInventoryFreeItemClass6: null
// AA_Inventory_idInventoryFreeItemClass7: null
// AA_Inventory_idInventoryFreeItemClass8: null
// AA_Inventory_idInventoryFreeItemClass9: null
// AA_Inventory_InStorageUpLimit: null
// AA_Inventory_OutStorageUpLimit: null
// AA_Inventory_AutoGenProject: null
// RowNo: "1"